
---
title: Tendencias de partidos y gobiernos respecto al día anterior
---


```{r graph04, echo=FALSE, out.width = '20%'}
datatable(vote_table, rownames=FALSE, colnames = c('Partido', 'Voto', 'Tendencia (voto)', 'Escaños', 'Tendencia (escaños)'), extensions = 'FixedColumns',
  options = list(
    dom = 'r',
    scrollX = TRUE,
    fixedColumns = TRUE, pageLength = 10
  )) %>%
  formatStyle(
    'diff_vote',
    color = styleInterval(c(-0.001, 0.001), c('red', 'black', 'green'))
  )  %>%
  formatStyle(
    'diff_seats',
    color = styleInterval(c(-0.001, 0.001), c('red', 'black', 'green'))
  ) %>%
  formatStyle('party', fontWeight = 'bold')
```



```{r graph1, echo=FALSE, out.width = '20%'}
myColors_gen <- c("#0000BA", "#9A0000", "#A9A9A9", "#C57420", "#FF3827", "#FF9300", "#04AAFF")
 
library(DT)

datatable(head(government_table, 6), rownames=FALSE, colnames = c('Tipo de gobierno', 'Probabilidad', 'Tendencia'), extensions = 'FixedColumns',
  options = list( dom= "t",
    scrollX = FALSE,
    fixedColumns = TRUE,
  scrollCollapse = TRUE, pageLength = 10
  )) %>%
  formatStyle(
    'diff_prob',
    color = styleInterval(c(-0.001, 0.001), c('red', 'black', 'green'))
  ) %>%
  formatStyle('party', fontWeight = 'bold')
```
_____

Alberto López Ortega _alberto.lopezortega@uzh.ch_ , [bertous](https://twitter.com/bertous)

