---
title: Predicción diaria de voto a partidos
---

Estos los resultados electorales más probables para los 5 grandes partidos [actualizados por última vez un día antes de las elecciones, el 27 de abril de 2019].

_________________


```{r graph03, echo=FALSE, out.width = '20%'}

hchart(
  vote_donut, "pie", hcaes(name = party, y = vote, color= colors),
  name = "Escaños",
  innerSize = "60%",
  startAngle = -90, endAngle = 90,
  dataLabels = list(format = "{point.name}, {point.vote} <br> ({point.seats})")
) %>% 
  # con la siguiente opción desactivamos los 'dataLabels' para que no 
  # exista infomración redundante
  hc_plotOptions(
    series = list(dataLabels = list(enabled = FALSE))
  ) %>% 
  hc_tooltip(
    useHTML = TRUE,
    style = list(fontSize = "20px"),
    headerFormat = "",
    pointFormat = "<div style='text-align: center;'> <b>{point.name}</b><br>{point.seats} escaños<br>{point.vote}% votos</div>",
    positioner = JS(
      "function () {
      
        /* one of the most important parts! */
        xp =  this.chart.chartWidth/2 - this.label.width/2
        yp =  this.chart.chartHeight/2 - this.label.height/1
      
        return { x: xp, y: yp };
      
      }"),
    shadow = FALSE,
    borderWidth = 0,
    backgroundColor = "transparent",
    hideDelay = 1000
  )


```

```{r graph04, echo=FALSE, out.width = '20%'}

hchart(vote_lines, "line", hcaes(date, vote, group = party), marker = list(enabled = TRUE), color=c("#E75D29" #good
        ,"#82ECAB"
        ,"#3C88D0" #good
        , "#DA3832" #good
        ,  "#623165"
        , "#75BE4C" ))  %>% 
  hc_tooltip(table = TRUE, valueDecimals = 2) %>% 
  hc_legend(
  align = "right",
  layout = "proximate"
) %>% 
  hc_tooltip(crosshairs = TRUE, backgroundColor = "#FBFEFF",
             shared = TRUE, borderWidth = 0, sort = TRUE,  table = TRUE) %>% 
  hc_yAxis(title = list(text = "Porcentaje estimados de voto %")) %>% 
  hc_xAxis(title = list(text = ""))

```

_____

Contacto: Alberto López Ortega _alberto.lopezortega@uzh.ch_ , [bertous](https://twitter.com/bertous)


